# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Tutorial-Namegame
version:      0.01
version_from: 
installdirs:  site
requires:
    Carp:                          0
    CGI::Application:              0
    CGI::Application::Plugin::AutoRunmode: 0
    CGI::Application::Plugin::Feedback: 0
    CGI::Application::Plugin::Forward: 0
    CGI::Application::Plugin::Session: 0
    Lingua::EN::Namegame:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
